### ISSUE TITLE
Icon is Blank after update

### ISSUE THREAD

**Issue by username227** [user-none/KDocker#136] opened 2024-09-24 02:03 UTC
**Describe the bug**
I have Thunderbird set to open with Kdocker at startup. Before the update to 6.0, the thunderbird icon would be used automatically. After the update, the icon is blank.

I have attempted to set the icon manually, and setting it manually works, but it is not persistent after a reboot, even when the settings are saved by kdocker.

**To Reproduce**
1. use Kdocker to dock Thunderbird
2. The icon in the tray is blank.

**Expected behavior**
Expected to see the Thunderbird icon.

**Screenshots**

![Screenshot from 2024-09-23 21-58-21](https://github.com/user-attachments/assets/9fe4c59f-ab41-4b21-8d02-433d6cbd5b3e)

**Desktop (please complete the following information):**
 - OS: Arch Linux - with Cinnamon DE
 - KDocker version: 6.0
 - Installation method: distro repo

**Additional context**

**Comment by Daxx** [comment] 2024-09-24 03:12
Duplicate of #135

> but it is not persistent after a reboot, even when the settings are saved by kdocker

Please attach _/tmp/kd.conf_ after running this (which just obscures your username, for modesty):

`sed 's|/home/[^/]*|<HOME>|' ~/.config/com.kdocker/KDocker.conf > /tmp/kd.conf`

**Comment by username227** [comment] 2024-09-24 11:35
[kd.conf.txt](https://github.com/user-attachments/files/17113856/kd.conf.txt)

**Comment by username227** [comment] 2024-09-24 11:49
literally no matter what I do, I'm unble to get the icon to appear. Starting thunderbird with kdocker -i option to force a custom icon still gives me a blank icon. the kdocker.conf file does have the custom icon set, but it's not respected. Not sure what's going on.

**Comment by username227** [comment] 2024-09-24 13:03
Two more things that might help narrow down the scope of the problem:
1) I tried kdocker with a different problem (firefox) with the same results; so it's not limited to thunderbird. I wonder if it might have something to do with its interaction with cinnamon.

2) I tried disabling 'balloon tile changes' for thunderbird and that also would not save after a restart. It could be that the settings are not being respected by the program globally.

**Comment by username227** [comment] 2024-09-24 13:12
EDIT: i retract the part about the balloon tile changes. It has now saved properly.

**Comment by username227** [comment] 2024-09-24 14:03
> Can you try KDocker with a non-mozilla app. Like the standard calculator app?

OK. Just tried with gnome-calculator. Same result.

**Comment by user-none** [comment] 2024-09-24 15:58
Does the corner of the window in the window frame show an icon?

**Comment by username227** [comment] 2024-09-24 16:34
> Does the corner of the window in the window frame show an icon?
 
You mean in thunderbird (or whatever other program we've tried) itself? No, I don't think so, but I'm not 100% sure what you mean.

**Comment by user-none** [comment] 2024-09-24 16:38
Here's an example with a calculator and emoji selector application. The indicated are the window icons I'm referring to. Do you have these on your windows?

<img width="357" alt="Screenshot 2024-09-24 at 12 35 27 PM" src="https://github.com/user-attachments/assets/3ac15988-d69c-441a-9d89-8f181bf7daed">

**Comment by username227** [comment] 2024-09-24 17:58
that's what I thought you meant. No, I don't have those on any of my applications. I could try to play with the settings to see if I can add them.

**Comment by user-none** [comment] 2024-09-24 18:03
> that's what I thought you meant. No, I don't have those on any of my applications. I could try to play with the settings to see if I can add them.

Okay I *think* what might be happening is KDocker first tires to read that icon. If it can't find an icon it tries another method (_NET_WM_ICON). What might be happening is there is actually an icon there but it's transparent. It's a valid image so fallback isn't happening. I'm going to make some changes to how the icon is read (hopefully tonight) that will attempt to deal with transparent icons.

@Daxx Maybe that's what's happening for you but I'm not sure. I hope what I have in mind will fix your problem too.

**Comment by user-none** [comment] 2024-09-24 18:18
It's the best explanation I can come up with. I installed Cinnamon on Fedora and the icons are showing in the dock for me.

**Comment by username227** [comment] 2024-09-24 18:49
quick question - when you installed Cinnamon on  Fedora, did you have icons in the top corner? I have been doing some research, and it seems like this requires a metacity theme, and cinnamon/mint dropped support for this somewhere around mint 19.2, or something. If you are seeing them, i'd be interested in knowing how.

**Comment by user-none** [comment] 2024-09-24 18:52
> when you installed Cinnamon on Fedora, did you have icons in the top corner? 

No, no icons in the corner.

I'm guessing on what's going on because several people are having this issue but for some reason I can't make it happen. I've tested (before and now after the 6.0 release) with Mate, Gnome, KDE, XFCE, Cinnamon, and LXDE. Firefox, Thunderbird, and multiple desktop default applications.

**Comment by user-none** [comment] 2024-09-24 22:01
A tray-icon branch has been made with some reworking of some of the icon code. It also added in some basic debug that gets written to the console. @username227, can you build this branch and see what it does. Run from the console and provide the output too please. @Daxx too if you can with Sublime.

**Comment by Daxx** [comment] 2024-09-25 03:28
> 2\. It could be that the settings are not being respected by the program globally.

I agree. V6.0 is ignoring "CustomIcon" settings and "Balloon title changes" and maybe others :(

**Comment by user-none** [comment] 2024-09-25 15:32
> I agree. V6.0 is ignoring "CustomIcon" settings and "Balloon title changes" and maybe others :(

Some settings are indeed broken. "CustomIcon" is definitely one of them.

**Comment by user-none** [comment] 2024-09-25 23:00
I check all options, setting them saving, unsetting, saving. Only custom icons were not working. Everything else appears fine.

**Comment by user-none** [comment] 2024-09-25 23:24
Settings fixes (and some additions) have been merged to main.

**Comment by username227** [comment] 2024-09-26 00:34
On a completely separate note, I have reworked the Arch git package on the AUR (kdocker-git) so that it builds again. I have reached out to the maintainer of that package to let him know. The new pkgbuild is here: https://github.com/username227/kdocker-git-package-fix. Hopefully whoever maintains it will either update it or give me rights to do it myself.

**Comment by Daxx** [comment] 2024-09-28 00:50
> Settings fixes (and some additions) have been merged to main.

Thanks, John @user-none, looking good now!

**Comment by user-none** [comment] 2024-09-28 15:21
6.1 released which closes this out.

**Closed by user-none** 2024-09-28 15:21 UTC
Labels: bug

**Comment by username227** [comment] 2024-10-13 13:04
Wanted to follow up and alert you. The latest commit seems to have done something to the fix you implemented here. The prior fix showed my Thunderbird application properly in the dock. however, the current commit shows only the backup icon that you programmed to show in the event that it can't find an icon.

**Comment by Daxx** [comment] 2024-10-13 13:41
> shows only the backup icon

See if there's any output from `kreadconfig5 --file ~/.config/com.kdocker/KDocker.conf --group "thunderbird" --key CustomIcon`
If it returns an icon location, make sure that file actually exists, else you'll see the backup icon.

**Comment by username227** [comment] 2024-10-13 15:18
Hmmm....OK, so you're right, the icon didn't exist, it was present under a different file name. When I added a second one with the correct file name it worked.

But here's the really strange thing - both versions of the program resulted in the same output, and the older version of the program worked properly to show the icon even though the icon wasn't the right name. that's bizarre.

**Comment by username227** [comment] 2024-10-13 15:22
Oh, anyway, while I have your attention, I finally got access to the kdocker-git package on the AUR and fixed it. 
The regular kdocker package is out of date, but whoever maintains it did update to 6.0, just never updated it to 6.1. Do you know this guy "Presence" who maintains that package?

**Comment by user-none** [comment] 2024-10-13 21:46
> Do you know this guy "Presence" who maintains that package?

Nope. I don't have anything to do with distro packaging.

> make sure that file actually exists, else you'll see the backup icon.

I'm going to make a change to have the icon not found icon be a different color when it's file not found from the config so it's easier to differentiate this situation.
